version: "3.8"

services:
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    environment:
      DB: postgresql
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: temporal

  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - temporal
